name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nasm build-essential libc6-dev-i386 gcc-multilib
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make limine
      run: make limine
    - name: make
      run: make
    - name: make iso
      run: make iso
    - name: Extract Short Commit ID
      id: extract_commit
      run: echo "SHORT_COMMIT_ID=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prerelease: true
        release_name: ${{ env.SHORT_COMMIT_ID }}
        tag_name: ${{ env.SHORT_COMMIT_ID }}

    - name: Upload Artifact to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./keystone.iso
        asset_name: keystone
        asset_content_type: application/octet-stream
    
